Katse-Entsho/Models/RegisterCredentials.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using System.Xml.Linq;

namespace Katse_Entsho.Models
{
    public class RegisterCredentials
    {
        [Required]
        public string UserName { get; set; }




        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm password")]
        [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }



    }
}

Katse-Entsho/Areas/Admin/Controllers/EmployeesController.cs
using Katse_Entsho.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Katse_Entsho.Models;
using Microsoft.AspNetCore.Authorization;


namespace Katse_Entsho.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    [Area("Admin")]
    public class EmployeesController : Controller
    {

        private readonly ILogger<EmployeesController> _logger;
        private UserManager<UserApp> userManager;
        private SignInManager<UserApp> SignInManager;

        private RoleManager<IdentityRole> roleManager;
        private KatseContext _context;

        public EmployeesController(KatseContext context, UserManager<UserApp> userMagr, SignInManager<UserApp> signInMgr, RoleManager<IdentityRole> roleMgr)
        {
            _context = context;
            userManager = userMagr;
            SignInManager = signInMgr;
            roleManager = roleMgr;

        }


        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Add()
        {
            ViewBag.Departments = _context.Departments.OrderBy(g => g.DepartmentName).ToList();

            return View();

        }

        [HttpGet]
        public IActionResult RegisterCredentials()
        {

            return View();
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.Action = "Edit";
            ViewBag.Departments = _context.Departments.OrderBy(g => g.DepartmentName).ToList();
            var salesPerson = _context.SalesPeople.Find(id);
            return View(salesPerson);
        }


        [HttpPost]
        public async Task<IActionResult> RegisterCredentials(RegisterCredentials user)
        {
            if (ModelState.IsValid)
            {
                Models.SalesPerson salesperson = new Models.SalesPerson();
                int userID = _context.SalesPeople.Max(x => x.UserID);

                salesperson = _context.SalesPeople.Find(userID);
                var usr = new UserApp
                {
                    UserName = user.UserName,
                    UserID = userID,
                    PhoneNumber = salesperson.SalesPersonContact.ToString(),
                    PhoneNumberConfirmed = true,
                    Email = salesperson.SalesPersonEmail,
                    EmailConfirmed = true,

                };


                // var testinga = _context.Patients.Where(x => x.PatiID == userID).Select(x => x.PatientName).FirstOrDefault();


                //return Content(testinga.ToString());

                var result = await userManager.CreateAsync(usr, user.Password);
                var resultss = await roleManager.CreateAsync(new IdentityRole("SalesPerson"));
                var resultROle = await userManager.AddToRoleAsync(usr, "SalesPerson");

                if (result.Succeeded)
                {
                    //   await SignInManager.SignInAsync(usr, isPersistent: false);
                    return RedirectToAction("Index", "Admin");
                }
            }
            return Content("Error Adding");
        }

        [HttpPost]
        public IActionResult Add(Models.SalesPerson salesPerson)
        {
            if (ModelState.IsValid)
            {
                _context.SalesPeople.Add(salesPerson);
                _context.SaveChanges();
                return RedirectToAction("RegisterCredentials");
            }
            else
            {
                ViewBag.Departments = _context.Departments.OrderBy(g => g.DepartmentName).ToList();
                return View();
            }
        }

        [HttpPost]
        public IActionResult Edit(Models.SalesPerson salesPerson)
        {
            if (ModelState.IsValid)
            {
   
                    _context.SalesPeople.Update(salesPerson);
                    _context.SaveChanges();
                    return RedirectToAction("Index", "Admin");     

            }
           

                return Content("Edit");
            
        }


    }
}

Katse-Entsho/Areas/Admin/Views/Employees/Add.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model SalesPerson
@{
    ViewBag.Title = "Register";

    string ProvincessID = " ";
    ViewBag.PRO = ProvincessID;
    <script>
        var srlProvs = "@ViewBag.Prov_s"
        var srlCities = "@ViewBag.City_s";
        var srlSuburbs = "@ViewBag.Suburb_s";
    </script>
}
<div class="illus-group-col">
    <h1 class="headline center"><span class="background_Matte">Manage Employees </span></h1>
    <h3 class="title">
        Administrator
    </h3>
    <br />


</div>

<h1></h1>

<div asp-validation-summary="All" class="text-danger"> </div>
<form method="post" asp-controller="Employees" asp-action="Add">

    <div class="form-group row">
        <div class="col-sm-9">

            <div class="col-sm-7">
                <label>First Name</label>
                <input asp-for="SalesPersonName" class="form-control" data-toggle="tooltip" data-placement="top" title="Provide Employee Name" placeholder="Employee Name"/>
            </div>
            <div class="col">
                <span asp-validation-for="SalesPersonName"
                      class="text-danger"></span>
            </div>
        </div>
    </div>

    <div class="form-group row">
        <div class="col-sm-9">

            <div class="col-sm-7">
                <label>Surname Name :</label>
                <input asp-for="SalesPersonSurname" class="form-control" data-toggle="tooltip" data-placement="top" title="Provide Employee Surname" placeholder="Employee Surname"/>
            </div>
            <div class="col">
                <span asp-validation-for="SalesPersonSurname"
                      class="text-danger"></span>
            </div>
        </div>
    </div>


    <div class="form-group row">
        <div class="col-sm-9">

            <div class="col-sm-7">
                <label>Gender :</label>
                <select asp-for="Gender" class="form-control" data-toggle="tooltip" data-placement="top" title="Provide Employee Gender" placeholder="Gender">
                    <option>Male</option>
                    <option>Female</option>
                </select>
            </div>
            <div class="col">
                <span asp-validation-for="Gender"
                      class="text-danger"></span>
            </div>
        </div>
    </div>



    <div class="form-group row">
        <div class="col-sm-9">

            <div class="col-7">
                <label>Contact Number :</label>
                <input asp-for="SalesPersonContact" class="form-control" data-toggle="tooltip" data-placement="top" title="Provide Employee phone number e.g 071 5154 234" placeholder="Employee Phone number"/>
            </div>
            <div class="col">
                <span asp-validation-for="SalesPersonContact"
                      class="text-danger"></span>
            </div>
        </div>
    </div>



    <div class="form-group">
        <div class="col-sm-9">
            <div class="col-sm-7 row">
                <label>Email Address :</label>
                <input asp-for="SalesPersonEmail" class="form-control" data-toggle="tooltip" data-placement="top" title="Provide Employee email e.g employeeName@domain.com" placeholder="Employee Email"/>
            </div>
            <div class="col">
                <span asp-validation-for="SalesPersonEmail"
                      class="text-danger"></span>
            </div>
        </div>
    </div>


    <div class="form-group">
        <div class="col-sm-9">
            <div class="col-sm-7 row">
                <label>Position :</label>
                <input asp-for="GradeLevel" class="form-control" data-toggle="tooltip" data-placement="top" title="Provide Employee Position e.g Junior IT Support" placeholder="Employee Position"/>
            </div>
            <div class="col">
                <span asp-validation-for="GradeLevel"
                      class="text-danger"></span>
            </div>
        </div>
    </div>

    <div class="form-group row">
        <div class="col-sm-9">

            <div class="col-sm-7">
                <label>Department :</label>
                <select asp-for="DeptID" asp-items="@(new SelectList(ViewBag.Departments, "DeptID", "DepartmentName"))" class="form-control" data-toggle="tooltip" data-placement="top" title="Assign Employee to Department" placeholder="Employee Department">
                </select>
            </div>
            <div class="col">
                <span asp-validation-for="DeptID"
                      class="text-danger"></span>
            </div>
        </div>
    </div>





    <script>
        var thisProvinces = document.getElementById('pageProvinceElement');
        var thisCities = document.getElementById('pageCityElement');
        var thisSuburbs = document.getElementById('pageSuburbElement');
        if (typeof srlProvs !== "undefined") {
            const allProvs = JSON.parse(srlProvs.replace(/&quot;/g, '"'));
            const allCities = JSON.parse(srlCities.replace(/&quot;/g, '"'));
            const allSuburbs = JSON.parse(srlSuburbs.replace(/&quot;/g, '"'));
            thisCities.innerHTML = "";
            for (var i = 0; i < allCities.length; i++) {
                var obj = allCities[i];
                let selectedProvince = thisProvinces.options[thisProvinces.selectedIndex].value;
                if (selectedProvince == obj["ProvinceID"]) {
                    let newOption = new Option(obj["Name"], obj["CityID"]);
                    thisCities.add(newOption, undefined);
                }
            }
            thisSuburbs.innerHTML = "";
            for (var i = 0; i < allSuburbs.length; i++) {
                var obj = allSuburbs[i];
                let selectedCity = thisCities.options[thisCities.selectedIndex].value;
                if (selectedCity == obj["CityID"]) {
                    let newOption = new Option(obj["Name"], obj["SuburbID"]);
                    thisSuburbs.add(newOption, undefined);
                }
            }
            if (thisProvinces) {
                thisProvinces.addEventListener("change", function () {
                    thisCities.innerHTML = "";
                    for (var i = 0; i < allCities.length; i++) {
                        var obj = allCities[i];
                        let selectedProvince = thisProvinces.options[thisProvinces.selectedIndex].value;
                        if (selectedProvince == obj["ProvinceID"]) {
                            let newOption = new Option(obj["Name"], obj["CityID"]);
                            thisCities.add(newOption, undefined);
                        }
                    }
                    thisSuburbs.innerHTML = "";
                    for (var i = 0; i < allSuburbs.length; i++) {
                        var obj = allSuburbs[i];
                        let selectedCity = thisCities.options[thisCities.selectedIndex].value;
                        if (selectedCity == obj["CityID"]) {
                            let newOption = new Option(obj["Name"], obj["SuburbID"]);
                            thisSuburbs.add(newOption, undefined);
                        }
                    }
                })
            }
            if (thisCities) {
                console.log("prov defined");
                thisCities.addEventListener("change", function () {
                    thisSuburbs.innerHTML = "";
                    for (var i = 0; i < allSuburbs.length; i++) {
                        var obj = allSuburbs[i];
                        let selectedCity = thisCities.options[thisCities.selectedIndex].value;
                        console.log(selectedCity);
                        if (selectedCity == obj["CityID"]) {
                            let newOption = new Option(obj["Name"], obj["SuburbID"]);
                            thisSuburbs.add(newOption, undefined);
                        }
                    }
                });
            }
        }</script>



    <div class="col-sm-2 align-content-end">
        <button type="submit" class="btn btn-danger" form-control>
            Save
        </button>

        <button class="btn btn-danger" asp-controller="Admin" asp-action="Index">Cancel</button>
    </div>


</form>

Katse-Entsho/Areas/Admin/Views/Employees/Edit.cshtml
@model SalesPerson
@{
    ViewBag.Title = "Register";

    string ProvincessID = " ";
    ViewBag.PRO = ProvincessID;
    <script>
        var srlProvs = "@ViewBag.Prov_s"
        var srlCities = "@ViewBag.City_s";
        var srlSuburbs = "@ViewBag.Suburb_s";
    </script>
}


<div class="illus-group-col">
    <h1 class="headline center"><span class="background_Matte">Manage Employees </span></h1>
  
    <br />


</div>

<div asp-validation-summary="All" class="text-danger"> </div>
<form method="post" asp-controller="Employees" asp-action="Edit">

    <div class="form-group row">
        <div class="col-sm-9">

            <div class="col-sm-7">
                <label>First Name</label>
                <input asp-for="SalesPersonName" class="form-control" data-toggle="tooltip" data-placement="top" title="Provide Employee Name" placeholder="Employee Name" />
            </div>
            <div class="col">
                <span asp-validation-for="SalesPersonName"
                      class="text-danger"></span>
            </div>
        </div>
    </div>

    <div class="form-group row" hidden="hidden">
        <div class="col-sm-9">

            <div class="col-sm-7">
                <label>First Name</label>
                <input asp-for="UserID" class="form-control" />
            </div>
            <div class="col">
                <span asp-validation-for="UserID"
                      class="text-danger"></span>
            </div>
        </div>
    </div>

    <div class="form-group row">
        <div class="col-sm-9">

            <div class="col-sm-7">
                <label>Surname Name :</label>
                <input asp-for="SalesPersonSurname" class="form-control" data-toggle="tooltip" data-placement="top" title="Provide Employee Surname" placeholder="Employee Surname"/>
            </div>
            <div class="col">
                <span asp-validation-for="SalesPersonSurname"
                      class="text-danger"></span>
            </div>
        </div>
    </div>


    <div class="form-group row">
        <div class="col-sm-9">

            <div class="col-sm-7">
                <label>Gender :</label>
                <select asp-for="Gender" class="form-control" data-toggle="tooltip" data-placement="top" title="Provide Employee Gender" placeholder="Gender">
                    <option>Male</option>
                    <option>Female</option>
                </select>
            </div>
            <div class="col">
                <span asp-validation-for="Gender"
                      class="text-danger"></span>
            </div>
        </div>
    </div>



    <div class="form-group row">
        <div class="col-sm-9">

            <div class="col-7">
                <label>Contact Number :</label>
                <input asp-for="SalesPersonContact" class="form-control" data-toggle="tooltip" data-placement="top" title="Provide Employee phone number e.g 071 5154 234" placeholder="Employee Phone number" />
            </div>
            <div class="col">
                <span asp-validation-for="SalesPersonContact"
                      class="text-danger"></span>
            </div>
        </div>
    </div>



    <div class="form-group">
        <div class="col-sm-9">
            <div class="col-sm-7 row">
                <label>Email Address :</label>
                <input asp-for="SalesPersonEmail" class="form-control" data-toggle="tooltip" data-placement="top" title="Provide Employee email e.g employeeName@domain.com" placeholder="Employee Email" />
            </div>
            <div class="col">
                <span asp-validation-for="SalesPersonEmail"
                      class="text-danger"></span>
            </div>
        </div>
    </div>


    <div class="form-group">
        <div class="col-sm-9">
            <div class="col-sm-7 row">
                <label>Position :</label>
                <input asp-for="GradeLevel" class="form-control" data-toggle="tooltip" data-placement="top" title="Provide Employee Position e.g Junior IT Support" placeholder="Employee Position"/>
            </div>
            <div class="col">
                <span asp-validation-for="GradeLevel"
                      class="text-danger"></span>
            </div>
        </div>
    </div>

    <div class="form-group row">
        <div class="col-sm-9">

            <div class="col-sm-7">
                <label>Department </label>
                <select asp-for="DeptID" asp-items="@(new SelectList(ViewBag.Departments, "DeptID", "DepartmentName"))" class="form-control" data-toggle="tooltip" data-placement="top" title="Assign Employee to Department" placeholder="Employee Department">
                </select>
            </div>
            <div class="col">
                <span asp-validation-for="DeptID"
                      class="text-danger"></span>
            </div>
        </div>
    </div>





    <script>
        var thisProvinces = document.getElementById('pageProvinceElement');
        var thisCities = document.getElementById('pageCityElement');
        var thisSuburbs = document.getElementById('pageSuburbElement');
        if (typeof srlProvs !== "undefined") {
            const allProvs = JSON.parse(srlProvs.replace(/&quot;/g, '"'));
            const allCities = JSON.parse(srlCities.replace(/&quot;/g, '"'));
            const allSuburbs = JSON.parse(srlSuburbs.replace(/&quot;/g, '"'));
            thisCities.innerHTML = "";
            for (var i = 0; i < allCities.length; i++) {
                var obj = allCities[i];
                let selectedProvince = thisProvinces.options[thisProvinces.selectedIndex].value;
                if (selectedProvince == obj["ProvinceID"]) {
                    let newOption = new Option(obj["Name"], obj["CityID"]);
                    thisCities.add(newOption, undefined);
                }
            }
            thisSuburbs.innerHTML = "";
            for (var i = 0; i < allSuburbs.length; i++) {
                var obj = allSuburbs[i];
                let selectedCity = thisCities.options[thisCities.selectedIndex].value;
                if (selectedCity == obj["CityID"]) {
                    let newOption = new Option(obj["Name"], obj["SuburbID"]);
                    thisSuburbs.add(newOption, undefined);
                }
            }
            if (thisProvinces) {
                thisProvinces.addEventListener("change", function () {
                    thisCities.innerHTML = "";
                    for (var i = 0; i < allCities.length; i++) {
                        var obj = allCities[i];
                        let selectedProvince = thisProvinces.options[thisProvinces.selectedIndex].value;
                        if (selectedProvince == obj["ProvinceID"]) {
                            let newOption = new Option(obj["Name"], obj["CityID"]);
                            thisCities.add(newOption, undefined);
                        }
                    }
                    thisSuburbs.innerHTML = "";
                    for (var i = 0; i < allSuburbs.length; i++) {
                        var obj = allSuburbs[i];
                        let selectedCity = thisCities.options[thisCities.selectedIndex].value;
                        if (selectedCity == obj["CityID"]) {
                            let newOption = new Option(obj["Name"], obj["SuburbID"]);
                            thisSuburbs.add(newOption, undefined);
                        }
                    }
                })
            }
            if (thisCities) {
                console.log("prov defined");
                thisCities.addEventListener("change", function () {
                    thisSuburbs.innerHTML = "";
                    for (var i = 0; i < allSuburbs.length; i++) {
                        var obj = allSuburbs[i];
                        let selectedCity = thisCities.options[thisCities.selectedIndex].value;
                        console.log(selectedCity);
                        if (selectedCity == obj["CityID"]) {
                            let newOption = new Option(obj["Name"], obj["SuburbID"]);
                            thisSuburbs.add(newOption, undefined);
                        }
                    }
                });
            }
        }</script>



    <div class="col-sm-2 align-content-end">
        <button type="submit" class="btn btn-danger" form-control>
            Save
        </button>

        <button class="btn btn-danger" asp-controller="Admin" asp-action="Index">Cancel</button>
    </div>


</form>

Katse-Entsho/Areas/Admin/Views/Employees/Index.cshtml
<h1>Employees
    </h1>

Katse-Entsho/Areas/Admin/Views/Employees/RegisterCredentials.cshtml
@model RegisterCredentials

@{
    ViewBag.Title = "Register";
}

<h1>Register</h1>

<div asp-validation-summary= "All" class="text-danger"> </div>
    <form method="post" asp-controller="Employees" asp-action="RegisterCredentials">

        <div class="form-group row align-content-center LogInCredentials">
           <div class="col-sm-9">
            <div class="col-sm-7">
                <label>UserName: </label>
                <input asp-for="UserName" class="form-control" data-toggle="tooltip" data-placement="top" title="Provide Employee UserName e.g EmployeeNAme@domain.com" placeholder="Employee UserName"/>
            </div>
         </div>
        </div>

        <div class="col">
            <span asp-validation-for="UserName" class="text-danger">

            </span>
        </div>

        <div class="form-group row">
            <div class="col-sm-9">
             <div class="col-sm-7">
                 <label>Password: </label>
                <input type="password" asp-for="Password" class="form-control" data-toggle="tooltip" data-placement="top" title="Provide Employee Password" placeholder="Password"/>
            </div>
             </div>
            <div class="col">
            <span asp-validation-for="Password" class="text-danger">

            </span>
             </div>
        </div>

        <div class="form-group row">
             <div class="col-sm-9"> 
             <div class="col-sm-7">
                 <label>Confirm Password: </label>
                <input type="password" asp-for="ConfirmPassword" class="form-control" data-toggle="tooltip" data-placement="top" title="Re-type Password Provided above" placeholder="Confirm Password"/>
            </div>
            </div>

            <div class="col">
            <span asp-validation-for="ConfirmPassword" class="text-danger">

            </span>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-4"> 
                <button type="submit" class="btn btn-danger" >Register</button> 
                <button asp-controller="Account" asp-action="Login" class="btn btn-danger">Cancel</button>
            </div>
        </div>
     

    </form>