Katse-Entsho/Models/Department.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Katse_Entsho.Models
{
    public class Department
    {

        [Key]
        public int DeptID { get; set; }


        public string DepartmentName { get; set; }

        public string Description { get; set; }


        public ICollection<SalesPerson> SalesPeople { get; set; }
    }
}

Katse-Entsho/Areas/Admin/Controllers/DepartmentController.cs
using Katse_Entsho.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Katse_Entsho.Areas.Admin.Controllers
{

    [Authorize(Roles = "Admin")]
    [Area("Admin")]
    public class DepartmentController : Controller
    {

        private KatseContext _context;
        

        public DepartmentController(KatseContext context)
        {
            _context = context;
        }


        public IActionResult Index()
        {
            var department = _context.Departments.ToList();
            return View(department);
        }
        
        public IActionResult Add()
        {

            return View("Edit", new Models.Department());

        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var depart = _context.Departments.Find(id);
            return View(depart);
        }


        [HttpPost]
        public IActionResult Delete(Models.Department department)
        {
            _context.Departments.Remove(department);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }


        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.Action = "Edit";
         
            var department = _context.Departments.Find(id);
            return View(department);
        }

        [HttpPost]
        public IActionResult Edit(Models.Department department)
        {

            if (department.DeptID == 0)
            {

                if (ModelState.IsValid)
                {
                    _context.Departments.Add(department);
                    _context.SaveChanges();
                    return RedirectToAction("Index");

                }
                else
                {
                    return Content("No direction");
                }

            }

            else
            {
                _context.Departments.Update(department);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }



        }

    }
}

Katse-Entsho/Areas/Admin/Views/Department/Delete.cshtml
@model Department
@{ 
    ViewBag.Title = "Delete Department";
}

<h2>Confirm Deletion</h2>

<h3>@Model.DepartmentName</h3>

<form asp-action="Delete" method="post">
    <input type="hidden" asp-for="DeptID"/>

    <button type="submit" class="btn btn-danger"> Yes</button>
    <a asp-controller="Department" asp-action="Index" class="btn btn-danger">Cancel</a>
</form>

Katse-Entsho/Areas/Admin/Views/Department/Edit.cshtml
@model Department
@{
    Layout = "_LayoutAdmin";
    string ProvincessID = " ";
    ViewBag.PRO = ProvincessID;
  
}

<div class="illus-group-col">
    <h1 class="headline center"><span class="background_Matte">Department Management </span></h1>
    <h3 class="title">
        Administrator
    </h3>
    <br />


</div>



<form method="post" asp-controller="Department" asp-action="Edit">
    <div asp-validation-summary="All" class="text-danger"> </div>

    <div class="form-group row">
        <div class="col-sm-9">
            <label>Department Name :</label>
            <div class="col-sm-7">
                <input asp-for="DepartmentName" data-toggle="tooltip" data-placement="top" title="Type department Name" placeholder="Department Name" form-control" />
            </div>
            <div class="col">
                <span asp-validation-for="DepartmentName"
                      class="text-danger"></span>
            </div>
        </div>
    </div>

    <div class="form-group row" hidden="hidden">
        <div class="col-sm-9">
            <label>DeptID :</label>
            <div class="col-sm-7">
                <input asp-for="DeptID" class="form-control" />
            </div>
            <div class="col">
                <span asp-validation-for="DeptID"
                      class="text-danger"></span>
            </div>
        </div>
    </div>



    <div class="form-group row">
        <div class="col-sm-9">
            <label>Description :</label>
            <div class="col-sm-7">
                <input type="text" asp-for="Description" data-toggle="tooltip" data-placement="top" title="Provide description of Department" placeholder="Department Description" class="form-control" />
            </div>
            <div class="col">
                <span asp-validation-for="Description"
                      class="text-danger"></span>
            </div>
        </div>
    </div>





    <div class="col-sm-2 align-content-end">
        <button type="submit" class="btn btn-primary text-capitalize">
            Save
        </button>

        <button class="btn btn-primary text-capitalize" asp-controller="Department" asp-action="Index">
            Cancel
        </button>
    </div>
</form>

Katse-Entsho/Areas/Admin/Views/Department/Index.cshtml
@model List<Department>
@{
    ViewBag.Title = "Departments";
    Layout = "_LayoutAdmin";
}

<div class="illus-group-col">
    <h1 class="headline center"><span class="background_Matte">Welcome </span></h1>
    <h3 class="title">
        Administrator
    </h3>
    <br />


</div>

<div class="box-columned box-spaced-between">
    <div class="">
        <a asp-controller="Department" asp-action="Add"
           class="btn btn-primary">Add</a>
    </div>
    <div class="sortbtn">
        <button type="button" class="btn btn-primary dropdown-toggle"
                id="sortDropdownBtn" data-toggle="dropdown"
                aria-expanded="false">
            Sort by
        </button>
        <ul class="dropdown-menu" aria-labelledby="sortDropdownBtn">
            <li class="dropdown-item">
                <a asp-controller="Doctor" asp-action="Index" asp-route-sortBy="none">
                    -----
                </a>
            </li>
            <li class="dropdown-item">
                <a asp-controller="Doctor" asp-action="Index" asp-route-sortBy="name">
                    Name
                </a>
            </li>
            <li class="dropdown-item">
                <a asp-controller="Doctor" asp-action="Index" asp-route-sortBy="suburb">
                    Suburb
                </a>
            </li>
            <li class="dropdown-item">
                <a asp-controller="Doctor" asp-action="Index" asp-route-sortBy="medprac">
                    Medical Practice
                </a>
            </li>
            <li class="dropdown-item">
                <a asp-controller="Doctor" asp-action="Index" asp-route-sortBy="status">
                    Status
                </a>
            </li>
        </ul>
    </div>
</div>

<table class="d-table">
    <thead>
        <tr>
            <th>Department</th>
            <th>Description</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var department in Model)
        {
            // int num = medication.MedicationIngredients.Where(s => s.MedicationID == medication.MedicationID).Select(v => v.ActiveIngredientID).FirstOrDefault();

            <tr>
                <td>@department.DepartmentName </td>
                <td>@department.Description </td>
                

             

                <td>

                    <a asp-controller="Department" asp-action="Edit"
                       asp-route-id="@department.DeptID">Edit</a>
                    <a asp-controller="Department" asp-action="Delete"
                       asp-route-id="@department.DeptID">Delete</a>
                <td>
            </tr>
        }
    </tbody>


</table>